// Store snapshot — P holds current values of all stores, updated via subscriptions.
// Canvas render code reads P.* (synchronous), Svelte components bind $store directly.

import * as Phys from '@stores/physics';
import * as Eff  from '@stores/effects';
import * as Bg   from '@stores/background';
import * as Uw   from '@stores/underwater';
import * as Sp   from '@stores/spotlight';
import * as Duo  from '@stores/duolink';
import * as Thr  from '@stores/threshold';
import * as Dit  from '@stores/dither';
import { TIMESCALE } from '@stores/speed';

export interface PhysicsSnapshot {
  BLOB_PARTICLE_COUNT: number;
  BLOB_REST_RADIUS: number;
  BELL_RADIUS: number;
  BLOB_SPRING_K: number;
  BLOB_DAMPING: number;
  BLOB_JITTER: number;
  BLOB_EDGE_DIST: number;
  NODE_BASE_RADIUS: number;
  BLOB_EXPAND_SCALE: number;
  BLOB_EXPAND_DECAY: number;
  TENTACLE_SPREAD_BOOST: number;
  TENTACLE_SPREAD_DECAY: number;
  BLOB_DRIFT_MAX: number;
  BLOB_DRIFT_ACCEL: number;
  BLOB_BEAT_KICK: number;
  BLOB_BEAT_KICK_DECAY: number;
  BLOB_MARGIN: number;
  TOP_CLEAR: number;
  ENERGY_MAX: number;
  ENERGY_RECHARGE: number;
  KICK_ACCEL: number;
  DRAG_MOMENTUM: number;
  TENTACLE_COUNT: number;
  TENTACLE_SEG_LEN: number;
  CLAM_SHELL_W: number;
  CLAM_SHELL_H: number;
  CLAM_SHELL_BLOW: number;
  CLAM_LIP_OPEN: number;
  CLAM_SNAP_FORCE: number;
  CLAM_SNAP_SPREAD: number;
  CLAM_SPIN_MAX: number;
  CLAM_GRAVITY: number;
  CLAM_WATER_DRAG: number;
  CLAM_SPIN_DECAY: number;
  CLAM_SNAP_SPRING: number;
  CLAM_SNAP_DAMP: number;
  CLAM_EDGE_DIST: number;
  CLAM_MARGIN: number;
  SHOCKWAVE_SPEED: number;
  SHOCKWAVE_MAX_R: number;
  POLYGON_MAX_SCALE: number;
  POLYGON_EXPAND_RATE: number;
  INFLATE_ENABLED: boolean;
  INFLATE_BOOST: number;
  INFLATE_DECAY: number;
  INFLATE_MAX: number;
  BLOB_FLASH_ENABLED: boolean;
  BLOB_FLASH_HZ: number;
  BLOB_FLASH_R: number;
  BLOB_FLASH_G: number;
  BLOB_FLASH_B: number;
  BLOB_FLASH_RANDOM: boolean;
  BLOB_FLASH_SLOPE: number;
  BLOB_FLASH_FADE_IN: number;
  BLOB_FLASH_FADE_OUT: number;
  BLOB_FLASH_ALL: boolean;
  PARTICLE_TRIGGER_ENABLED: boolean;
  PARTICLE_TRIGGER_HZ: number;
  PARTICLE_TRIGGER_BOOST: number;
  PARTICLE_TRIGGER_SLOPE: number;
  PARTICLE_TRIGGER_FADE_IN: number;
  PARTICLE_TRIGGER_FADE_OUT: number;
  PARTICLE_ENERGY_ENABLED: boolean;
  PARTICLE_ENERGY_MIN: number;
  PARTICLE_ENERGY_MAX: number;
  BG_R: number;
  BG_G: number;
  BG_B: number;
  BG_TRAIL_ALPHA: number;
  BG_ENERGY_MAX_ALPHA: number;
  SUB_BAND_HEIGHT: number;
  SUB_MAX_ALPHA: number;
  SUB_R: number;
  SUB_G: number;
  SUB_B: number;
  UW_CAUSTICS_ENABLED: boolean;
  UW_CAUSTICS_ALPHA: number;
  UW_CAUSTICS_SPEED: number;
  UW_PARTICLES_ENABLED: boolean;
  UW_PARTICLES_ALPHA: number;
  UW_PARTICLES_SPEED: number;
  UW_BLOB_R1: number; UW_BLOB_G1: number; UW_BLOB_B1: number;
  UW_BLOB_R2: number; UW_BLOB_G2: number; UW_BLOB_B2: number;
  UW_PARTICLES_R: number; UW_PARTICLES_G: number; UW_PARTICLES_B: number;
  SPOTLIGHT_ENABLED: boolean;
  SOLO_THRESHOLD_MS: number;
  SPOTLIGHT_MAX_ALPHA: number;
  SPOTLIGHT_RADIUS_MULT: number;
  SPOTLIGHT_FADE_IN: number;
  SPOTLIGHT_FADE_OUT: number;
  DUO_LINK_ENABLED: boolean;
  DUO_THRESHOLD_MS: number;
  DUO_LINK_MAX_ALPHA: number;
  DUO_SYNC_WINDOW: number;
  DUO_SYNC_TOLERANCE: number;
  DUO_SYNC_MIN_MATCHES: number;
  DUO_LINK_EDGE_DIST: number;
  DUO_LINK_PARTICLE_COUNT: number;
  DUO_LINK_SPREAD: number;
  DUO_FADE_IN: number;
  DUO_FADE_OUT: number;
  IDLE_DECAY_RATE: number;
  FREQ_DECAY_BIAS: number;
  MIN_FLUX_FLOOR: number;
  DITHER_ENABLED: boolean;
  DITHER_PIXEL_SIZE: number;
  DITHER_LEVELS: number;
  DITHER_OPACITY: number;
  DITHER_TINT_ENABLED: boolean;
  DITHER_TINT_R: number; DITHER_TINT_G: number; DITHER_TINT_B: number;
  DITHER_TINT_STR: number;
  DITHER_SCAN_ENABLED: boolean;
  DITHER_SCAN_ALPHA: number;
  DITHER_SCAN_GAP: number;
  BG_RANDOMIZE_ENABLED: boolean;
  BG_RANDOMIZE_RANGE: number;
  BG_RANDOMIZE_HZ: number;
  BG_RANDOMIZE_SLOPE: number;
  BG_RANDOMIZE_FADE_IN: number;
  BG_RANDOMIZE_FADE_OUT: number;
  LR_MODE_ENABLED: boolean;
  LR_HZ: number;
  LR_WINDOW_MS: number;
  LR_FLASH_SLOPE: number;
  LR_CENTER_REDUCTION: number;
  LR_FADE_IN: number;
  LR_FADE_OUT: number;
  LR_LEFT_R: number; LR_LEFT_G: number; LR_LEFT_B: number;
  LR_RIGHT_R: number; LR_RIGHT_G: number; LR_RIGHT_B: number;
  RIPPLE_ENABLED: boolean;
  RIPPLE_HZ: number;
  RIPPLE_MAX_R: number;
  RIPPLE_SPEED: number;
  RIPPLE_ALPHA: number;
  RIPPLE_BRIGHTEN: number;
  RIPPLE_RING_COUNT: number;
  RIPPLE_WAVELENGTH: number;
  TIMESCALE: number;
}

export const P = {} as PhysicsSnapshot;

export function initStoreSnapshots() {
  Phys.BLOB_PARTICLE_COUNT.subscribe(v  => { P.BLOB_PARTICLE_COUNT  = v; });
  Phys.BLOB_REST_RADIUS.subscribe(v     => { P.BLOB_REST_RADIUS     = v; });
  Phys.BELL_RADIUS.subscribe(v          => { P.BELL_RADIUS          = v; });
  Phys.BLOB_SPRING_K.subscribe(v        => { P.BLOB_SPRING_K        = v; });
  Phys.BLOB_DAMPING.subscribe(v         => { P.BLOB_DAMPING         = v; });
  Phys.BLOB_JITTER.subscribe(v          => { P.BLOB_JITTER          = v; });
  Phys.BLOB_EDGE_DIST.subscribe(v       => { P.BLOB_EDGE_DIST       = v; });
  Phys.NODE_BASE_RADIUS.subscribe(v     => { P.NODE_BASE_RADIUS     = v; });
  Phys.BLOB_EXPAND_SCALE.subscribe(v    => { P.BLOB_EXPAND_SCALE    = v; });
  Phys.BLOB_EXPAND_DECAY.subscribe(v    => { P.BLOB_EXPAND_DECAY    = v; });
  Phys.TENTACLE_SPREAD_BOOST.subscribe(v => { P.TENTACLE_SPREAD_BOOST = v; });
  Phys.TENTACLE_SPREAD_DECAY.subscribe(v => { P.TENTACLE_SPREAD_DECAY = v; });
  Phys.BLOB_DRIFT_MAX.subscribe(v       => { P.BLOB_DRIFT_MAX       = v; });
  Phys.BLOB_DRIFT_ACCEL.subscribe(v     => { P.BLOB_DRIFT_ACCEL     = v; });
  Phys.BLOB_BEAT_KICK.subscribe(v       => { P.BLOB_BEAT_KICK       = v; });
  Phys.BLOB_BEAT_KICK_DECAY.subscribe(v => { P.BLOB_BEAT_KICK_DECAY = v; });
  Phys.BLOB_MARGIN.subscribe(v          => { P.BLOB_MARGIN          = v; });
  Phys.TOP_CLEAR.subscribe(v            => { P.TOP_CLEAR            = v; });
  Phys.ENERGY_MAX.subscribe(v           => { P.ENERGY_MAX           = v; });
  Phys.ENERGY_RECHARGE.subscribe(v      => { P.ENERGY_RECHARGE      = v; });
  Phys.KICK_ACCEL.subscribe(v           => { P.KICK_ACCEL           = v; });
  Phys.DRAG_MOMENTUM.subscribe(v        => { P.DRAG_MOMENTUM        = v; });
  Phys.TENTACLE_COUNT.subscribe(v       => { P.TENTACLE_COUNT       = v; });
  Phys.TENTACLE_SEG_LEN.subscribe(v     => { P.TENTACLE_SEG_LEN     = v; });
  Phys.CLAM_SHELL_W.subscribe(v         => { P.CLAM_SHELL_W         = v; });
  Phys.CLAM_SHELL_H.subscribe(v         => { P.CLAM_SHELL_H         = v; });
  Phys.CLAM_SHELL_BLOW.subscribe(v      => { P.CLAM_SHELL_BLOW      = v; });
  Phys.CLAM_LIP_OPEN.subscribe(v        => { P.CLAM_LIP_OPEN        = v; });
  Phys.CLAM_SNAP_FORCE.subscribe(v      => { P.CLAM_SNAP_FORCE      = v; });
  Phys.CLAM_SNAP_SPREAD.subscribe(v     => { P.CLAM_SNAP_SPREAD     = v; });
  Phys.CLAM_SPIN_MAX.subscribe(v        => { P.CLAM_SPIN_MAX        = v; });
  Phys.CLAM_GRAVITY.subscribe(v         => { P.CLAM_GRAVITY         = v; });
  Phys.CLAM_WATER_DRAG.subscribe(v      => { P.CLAM_WATER_DRAG      = v; });
  Phys.CLAM_SPIN_DECAY.subscribe(v      => { P.CLAM_SPIN_DECAY      = v; });
  Phys.CLAM_SNAP_SPRING.subscribe(v     => { P.CLAM_SNAP_SPRING     = v; });
  Phys.CLAM_SNAP_DAMP.subscribe(v       => { P.CLAM_SNAP_DAMP       = v; });
  Phys.CLAM_EDGE_DIST.subscribe(v       => { P.CLAM_EDGE_DIST       = v; });
  Phys.CLAM_MARGIN.subscribe(v          => { P.CLAM_MARGIN          = v; });
  Eff.SHOCKWAVE_SPEED.subscribe(v       => { P.SHOCKWAVE_SPEED      = v; });
  Eff.SHOCKWAVE_MAX_R.subscribe(v       => { P.SHOCKWAVE_MAX_R      = v; });
  Eff.POLYGON_MAX_SCALE.subscribe(v     => { P.POLYGON_MAX_SCALE    = v; });
  Eff.POLYGON_EXPAND_RATE.subscribe(v   => { P.POLYGON_EXPAND_RATE  = v; });
  Eff.INFLATE_ENABLED.subscribe(v       => { P.INFLATE_ENABLED      = v; });
  Eff.INFLATE_BOOST.subscribe(v         => { P.INFLATE_BOOST        = v; });
  Eff.INFLATE_DECAY.subscribe(v         => { P.INFLATE_DECAY        = v; });
  Eff.INFLATE_MAX.subscribe(v           => { P.INFLATE_MAX          = v; });
  Eff.BLOB_FLASH_ENABLED.subscribe(v    => { P.BLOB_FLASH_ENABLED   = v; });
  Eff.BLOB_FLASH_HZ.subscribe(v         => { P.BLOB_FLASH_HZ        = v; });
  Eff.BLOB_FLASH_R.subscribe(v          => { P.BLOB_FLASH_R         = v; });
  Eff.BLOB_FLASH_G.subscribe(v          => { P.BLOB_FLASH_G         = v; });
  Eff.BLOB_FLASH_B.subscribe(v          => { P.BLOB_FLASH_B         = v; });
  Eff.BLOB_FLASH_RANDOM.subscribe(v     => { P.BLOB_FLASH_RANDOM    = v; });
  Eff.BLOB_FLASH_SLOPE.subscribe(v      => { P.BLOB_FLASH_SLOPE     = v; });
  Eff.BLOB_FLASH_FADE_IN.subscribe(v    => { P.BLOB_FLASH_FADE_IN   = v; });
  Eff.BLOB_FLASH_FADE_OUT.subscribe(v   => { P.BLOB_FLASH_FADE_OUT  = v; });
  Eff.BLOB_FLASH_ALL.subscribe(v        => { P.BLOB_FLASH_ALL       = v; });
  Eff.PARTICLE_TRIGGER_ENABLED.subscribe(v  => { P.PARTICLE_TRIGGER_ENABLED  = v; });
  Eff.PARTICLE_TRIGGER_HZ.subscribe(v       => { P.PARTICLE_TRIGGER_HZ       = v; });
  Eff.PARTICLE_TRIGGER_BOOST.subscribe(v    => { P.PARTICLE_TRIGGER_BOOST    = v; });
  Eff.PARTICLE_TRIGGER_SLOPE.subscribe(v    => { P.PARTICLE_TRIGGER_SLOPE    = v; });
  Eff.PARTICLE_TRIGGER_FADE_IN.subscribe(v  => { P.PARTICLE_TRIGGER_FADE_IN  = v; });
  Eff.PARTICLE_TRIGGER_FADE_OUT.subscribe(v => { P.PARTICLE_TRIGGER_FADE_OUT = v; });
  Eff.PARTICLE_ENERGY_ENABLED.subscribe(v   => { P.PARTICLE_ENERGY_ENABLED   = v; });
  Eff.PARTICLE_ENERGY_MIN.subscribe(v       => { P.PARTICLE_ENERGY_MIN       = v; });
  Eff.PARTICLE_ENERGY_MAX.subscribe(v       => { P.PARTICLE_ENERGY_MAX       = v; });
  Eff.BG_RANDOMIZE_ENABLED.subscribe(v  => { P.BG_RANDOMIZE_ENABLED  = v; });
  Eff.BG_RANDOMIZE_RANGE.subscribe(v    => { P.BG_RANDOMIZE_RANGE    = v; });
  Eff.BG_RANDOMIZE_HZ.subscribe(v       => { P.BG_RANDOMIZE_HZ       = v; });
  Eff.BG_RANDOMIZE_SLOPE.subscribe(v    => { P.BG_RANDOMIZE_SLOPE    = v; });
  Eff.BG_RANDOMIZE_FADE_IN.subscribe(v  => { P.BG_RANDOMIZE_FADE_IN  = v; });
  Eff.BG_RANDOMIZE_FADE_OUT.subscribe(v => { P.BG_RANDOMIZE_FADE_OUT = v; });
  Eff.LR_MODE_ENABLED.subscribe(v      => { P.LR_MODE_ENABLED     = v; });
  Eff.LR_HZ.subscribe(v               => { P.LR_HZ               = v; });
  Eff.LR_WINDOW_MS.subscribe(v        => { P.LR_WINDOW_MS         = v; });
  Eff.LR_FLASH_SLOPE.subscribe(v      => { P.LR_FLASH_SLOPE       = v; });
  Eff.LR_CENTER_REDUCTION.subscribe(v => { P.LR_CENTER_REDUCTION  = v; });
  Eff.LR_FADE_IN.subscribe(v          => { P.LR_FADE_IN           = v; });
  Eff.LR_FADE_OUT.subscribe(v         => { P.LR_FADE_OUT          = v; });
  Eff.LR_LEFT_R.subscribe(v  => { P.LR_LEFT_R  = v; }); Eff.LR_LEFT_G.subscribe(v  => { P.LR_LEFT_G  = v; }); Eff.LR_LEFT_B.subscribe(v  => { P.LR_LEFT_B  = v; });
  Eff.LR_RIGHT_R.subscribe(v => { P.LR_RIGHT_R = v; }); Eff.LR_RIGHT_G.subscribe(v => { P.LR_RIGHT_G = v; }); Eff.LR_RIGHT_B.subscribe(v => { P.LR_RIGHT_B = v; });
  Eff.RIPPLE_ENABLED.subscribe(v       => { P.RIPPLE_ENABLED    = v; });
  Eff.RIPPLE_HZ.subscribe(v            => { P.RIPPLE_HZ         = v; });
  Eff.RIPPLE_MAX_R.subscribe(v         => { P.RIPPLE_MAX_R      = v; });
  Eff.RIPPLE_SPEED.subscribe(v         => { P.RIPPLE_SPEED      = v; });
  Eff.RIPPLE_ALPHA.subscribe(v         => { P.RIPPLE_ALPHA      = v; });
  Eff.RIPPLE_BRIGHTEN.subscribe(v      => { P.RIPPLE_BRIGHTEN   = v; });
  Eff.RIPPLE_RING_COUNT.subscribe(v    => { P.RIPPLE_RING_COUNT = v; });
  Eff.RIPPLE_WAVELENGTH.subscribe(v    => { P.RIPPLE_WAVELENGTH = v; });
  Bg.BG_R.subscribe(v                   => { P.BG_R                 = v; });
  Bg.BG_G.subscribe(v                   => { P.BG_G                 = v; });
  Bg.BG_B.subscribe(v                   => { P.BG_B                 = v; });
  Bg.BG_TRAIL_ALPHA.subscribe(v         => { P.BG_TRAIL_ALPHA       = v; });
  Bg.BG_ENERGY_MAX_ALPHA.subscribe(v    => { P.BG_ENERGY_MAX_ALPHA  = v; });
  Bg.SUB_BAND_HEIGHT.subscribe(v        => { P.SUB_BAND_HEIGHT      = v; });
  Bg.SUB_MAX_ALPHA.subscribe(v          => { P.SUB_MAX_ALPHA        = v; });
  Bg.SUB_R.subscribe(v                  => { P.SUB_R                = v; });
  Bg.SUB_G.subscribe(v                  => { P.SUB_G                = v; });
  Bg.SUB_B.subscribe(v                  => { P.SUB_B                = v; });
  Uw.UW_CAUSTICS_ENABLED.subscribe(v    => { P.UW_CAUSTICS_ENABLED  = v; });
  Uw.UW_CAUSTICS_ALPHA.subscribe(v      => { P.UW_CAUSTICS_ALPHA    = v; });
  Uw.UW_CAUSTICS_SPEED.subscribe(v      => { P.UW_CAUSTICS_SPEED    = v; });
  Uw.UW_PARTICLES_ENABLED.subscribe(v   => { P.UW_PARTICLES_ENABLED = v; });
  Uw.UW_PARTICLES_ALPHA.subscribe(v     => { P.UW_PARTICLES_ALPHA   = v; });
  Uw.UW_PARTICLES_SPEED.subscribe(v     => { P.UW_PARTICLES_SPEED   = v; });
  Uw.UW_BLOB_R1.subscribe(v => { P.UW_BLOB_R1 = v; }); Uw.UW_BLOB_G1.subscribe(v => { P.UW_BLOB_G1 = v; }); Uw.UW_BLOB_B1.subscribe(v => { P.UW_BLOB_B1 = v; });
  Uw.UW_BLOB_R2.subscribe(v => { P.UW_BLOB_R2 = v; }); Uw.UW_BLOB_G2.subscribe(v => { P.UW_BLOB_G2 = v; }); Uw.UW_BLOB_B2.subscribe(v => { P.UW_BLOB_B2 = v; });
  Uw.UW_PARTICLES_R.subscribe(v => { P.UW_PARTICLES_R = v; }); Uw.UW_PARTICLES_G.subscribe(v => { P.UW_PARTICLES_G = v; }); Uw.UW_PARTICLES_B.subscribe(v => { P.UW_PARTICLES_B = v; });
  Sp.SPOTLIGHT_ENABLED.subscribe(v      => { P.SPOTLIGHT_ENABLED     = v; });
  Sp.SOLO_THRESHOLD_MS.subscribe(v      => { P.SOLO_THRESHOLD_MS     = v; });
  Sp.SPOTLIGHT_MAX_ALPHA.subscribe(v    => { P.SPOTLIGHT_MAX_ALPHA   = v; });
  Sp.SPOTLIGHT_RADIUS_MULT.subscribe(v  => { P.SPOTLIGHT_RADIUS_MULT = v; });
  Sp.SPOTLIGHT_FADE_IN.subscribe(v      => { P.SPOTLIGHT_FADE_IN     = v; });
  Sp.SPOTLIGHT_FADE_OUT.subscribe(v     => { P.SPOTLIGHT_FADE_OUT    = v; });
  Duo.DUO_LINK_ENABLED.subscribe(v         => { P.DUO_LINK_ENABLED        = v; });
  Duo.DUO_THRESHOLD_MS.subscribe(v         => { P.DUO_THRESHOLD_MS        = v; });
  Duo.DUO_LINK_MAX_ALPHA.subscribe(v       => { P.DUO_LINK_MAX_ALPHA      = v; });
  Duo.DUO_SYNC_WINDOW.subscribe(v          => { P.DUO_SYNC_WINDOW         = v; });
  Duo.DUO_SYNC_TOLERANCE.subscribe(v       => { P.DUO_SYNC_TOLERANCE      = v; });
  Duo.DUO_SYNC_MIN_MATCHES.subscribe(v     => { P.DUO_SYNC_MIN_MATCHES    = v; });
  Duo.DUO_LINK_EDGE_DIST.subscribe(v       => { P.DUO_LINK_EDGE_DIST      = v; });
  Duo.DUO_LINK_PARTICLE_COUNT.subscribe(v  => { P.DUO_LINK_PARTICLE_COUNT = v; });
  Duo.DUO_LINK_SPREAD.subscribe(v          => { P.DUO_LINK_SPREAD         = v; });
  Duo.DUO_FADE_IN.subscribe(v              => { P.DUO_FADE_IN             = v; });
  Duo.DUO_FADE_OUT.subscribe(v             => { P.DUO_FADE_OUT            = v; });
  Thr.IDLE_DECAY_RATE.subscribe(v  => { P.IDLE_DECAY_RATE = v; });
  Thr.FREQ_DECAY_BIAS.subscribe(v  => { P.FREQ_DECAY_BIAS = v; });
  Thr.MIN_FLUX_FLOOR.subscribe(v   => { P.MIN_FLUX_FLOOR  = v; });
  Dit.DITHER_ENABLED.subscribe(v      => { P.DITHER_ENABLED      = v; });
  Dit.DITHER_PIXEL_SIZE.subscribe(v   => { P.DITHER_PIXEL_SIZE   = v; });
  Dit.DITHER_LEVELS.subscribe(v       => { P.DITHER_LEVELS       = v; });
  Dit.DITHER_OPACITY.subscribe(v      => { P.DITHER_OPACITY      = v; });
  Dit.DITHER_TINT_ENABLED.subscribe(v => { P.DITHER_TINT_ENABLED = v; });
  Dit.DITHER_TINT_R.subscribe(v => { P.DITHER_TINT_R = v; }); Dit.DITHER_TINT_G.subscribe(v => { P.DITHER_TINT_G = v; }); Dit.DITHER_TINT_B.subscribe(v => { P.DITHER_TINT_B = v; });
  Dit.DITHER_TINT_STR.subscribe(v     => { P.DITHER_TINT_STR     = v; });
  Dit.DITHER_SCAN_ENABLED.subscribe(v => { P.DITHER_SCAN_ENABLED = v; });
  Dit.DITHER_SCAN_ALPHA.subscribe(v   => { P.DITHER_SCAN_ALPHA   = v; });
  Dit.DITHER_SCAN_GAP.subscribe(v     => { P.DITHER_SCAN_GAP     = v; });
  TIMESCALE.subscribe(v               => { P.TIMESCALE           = v; });
}
